### ISSUE TITLE
Commented out test due to failure but code is correct

### ISSUE THREAD

**Issue by joshuaneedham** [learn-co-students/sinatra-complex-forms-associations-v-000#645]
Not sure what is going on but after two different screenshares with mentors we were not able to figure out what the problem was. I commented out the test per mentor recommendation and moving on. Feel free to review my fork code for further investigation.

```
require 'spec_helper'

describe "Pets Controller" do
  describe "new action" do

    it "can visit '/pets/new'" do
      get '/pets/new'
      expect(last_response.status).to eq(200)
    end

    it " loads form to create a new pet" do
      visit '/pets/new'
      expect(page).to have_field('pet[name]')
    end

    # it "has a form with a checkbox for existing owners" do
    #   @owner1 = Owner.create(:name => "Cricky")
    #   @owner2 = Owner.create(:name => "Chris")

    #   visit '/pets/new'
    #   expect(page.has_unchecked_field?(@owner1.id)).to eq(true)
    #   expect(page.has_unchecked_field?(@owner2.id)).to eq(true)
    # end

    it "has a field for creating a new owner" do
      visit '/pets/new'
      expect(page).to have_field(:owner_name)
    end


    # it "creates a new pet and associates an existing owner" do
    #   @owner1 = Owner.create(:name => "Cricky")
    #   @owner2 = Owner.create(:name => "Chris")
    #   visit '/pets/new'
    #   fill_in "pet_name", :with => "Michael"
    #   check(@owner1.id)
    #   click_button "Create Pet"
    #   @pet = Pet.last
    #   expect(@pet.name).to eq("Michael")
    #   expect(@pet.owner.name).to eq("Cricky")
    # end

      it " creates a new pet and a new owner" do
      visit '/pets/new'
      fill_in "pet_name", :with => "Pippa"
      fill_in "owner_name", :with => "Mary Nelson"
      click_button "Create Pet"
      @owner = Owner.last
      @pet = Pet.last
      expect(@pet.name).to eq("Pippa")
      expect(@pet.owner.name).to eq("Mary Nelson")
    end

    # it "redirects to '/pets/:id' after form submissions" do
    #   @owner1 = Owner.create(:name => "Kristi")
    #   @owner2 = Owner.create(:name => "Kaitlin")
    #   visit '/pets/new'
    #   fill_in "pet_name", :with => "Joeseph"
    #   check(@owner2.id)
    #   click_button "Create Pet"
    #   @pet= Pet.last
    #   expect(page.current_path).to eq("/pets/#{@pet.id}")
    # end
  end

  describe "edit action" do
    before(:each) do
      @owner = Owner.create(:name => "Carla")
      @pet = Pet.create(:name => "Chewie", :owner_id => @owner.id)
    end

    it "can visit '/pets/:id/edit' " do
      get "/owners/#{@pet.id}/edit"
      expect(last_response.status).to eq(200)
    end

    it " loads form to edit a pet and his owner" do
      visit "/pets/#{@pet.id}/edit"
      expect(page).to have_field('pet[name]')
      expect(page.has_checked_field?(@owner.id)).to eq(true)
      expect(page).to have_field('owner[name]')
    end

     it "edit's the pet's name" do
      visit "/pets/#{@pet.id}/edit"
      fill_in "pet_name", :with => "Chewie Darling"
      click_button "Update Pet"
      expect(Pet.last.name).to eq("Chewie Darling")
    end

    # it "edit's the pet's owner with an existing owner" do
    #   @adam = Owner.create(:name => "Adam")
    #   visit "/pets/#{@pet.id}/edit"
    #   choose(@adam.id)
    #   click_button "Update Pet"
    #   expect(Pet.last.owner.name).to eq("Adam")
    # end

    it "edit's the pet's owner with a new owner" do
      visit "/pets/#{@pet.id}/edit"
      fill_in "owner_name", :with => "Samantha"
      click_button "Update Pet"
      expect(Pet.last.owner.name).to eq("Samantha")
    end


  end

end
```

**Comment by hcarnes** [comment]
Can you also include the error?

**Comment by joshuaneedham** [comment]
```
Owners Controller
  new action
    can visit '/owners/new'
    '/owners/new' loads form to create a new owner
    '/owners/new' form has a checkbox for existing pets
    '/owners/new' form has a field for creating a new pet
    '/owners/new' creates a new owner and associates an existing pet
    '/owners/new' creates a new owner and a new pet
    '/owners/new' redirects to '/owners/:id' after form submissions
  edit action
    can visit '/owners/:id/edit'
    '/owners/:id/edit' loads form to edit an owner and his pets
    edit's the owner's name
    edit's the owner's pets with an existing pet
    edit's the owner's pets with a new pet

Pets Controller
  new action
    can visit '/pets/new'
    loads form to create a new pet
    has a form with a checkbox for existing owners (FAILED - 1)
    has a field for creating a new owner
    creates a new pet and associates an existing owner (FAILED - 2)
    creates a new pet and a new owner
    redirects to '/pets/:id' after form submissions (FAILED - 3)
  edit action
    can visit '/pets/:id/edit'
    loads form to edit a pet and his owner
    edit's the pet's name
    edit's the pet's owner with an existing owner (FAILED - 4)
    edit's the pet's owner with a new owner

Failures:

  1) Pets Controller new action has a form with a checkbox for existing owners
     Failure/Error: expect(page.has_unchecked_field?(@owner1.id)).to eq(true)
     
       expected: true
            got: false
     
       (compared using ==)
     # ./spec/controllers/pets_controller_spec.rb:21:in `block (3 levels) in <top (required)>'

  2) Pets Controller new action creates a new pet and associates an existing owner
     Failure/Error: check(@owner1.id)
     
     Capybara::ElementNotFound:
       Unable to find visible checkbox 1 that is not disabled
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/finders.rb:314:in `block in synced_resolve'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/base.rb:81:in `synchronize'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/finders.rb:302:in `synced_resolve'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/finders.rb:37:in `find'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/actions.rb:300:in `block in _check_with_label'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/base.rb:85:in `synchronize'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/actions.rb:298:in `_check_with_label'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/actions.rb:140:in `check'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/session.rb:808:in `block (2 levels) in <class:Session>'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/controllers/pets_controller_spec.rb:36:in `block (3 levels) in <top (required)>'

  3) Pets Controller new action redirects to '/pets/:id' after form submissions
     Failure/Error: check(@owner2.id)
     
     Capybara::ElementNotFound:
       Unable to find visible checkbox 2 that is not disabled
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/finders.rb:314:in `block in synced_resolve'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/base.rb:81:in `synchronize'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/finders.rb:302:in `synced_resolve'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/finders.rb:37:in `find'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/actions.rb:300:in `block in _check_with_label'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/base.rb:85:in `synchronize'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/actions.rb:298:in `_check_with_label'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/actions.rb:140:in `check'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/session.rb:808:in `block (2 levels) in <class:Session>'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/controllers/pets_controller_spec.rb:59:in `block (3 levels) in <top (required)>'

  4) Pets Controller edit action edit's the pet's owner with an existing owner
     Failure/Error: choose(@adam.id)
     
     Capybara::ElementNotFound:
       Unable to find visible radio button 2 that is not disabled
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/finders.rb:314:in `block in synced_resolve'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/base.rb:81:in `synchronize'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/finders.rb:302:in `synced_resolve'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/finders.rb:37:in `find'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/actions.rb:300:in `block in _check_with_label'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/base.rb:85:in `synchronize'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/actions.rb:298:in `_check_with_label'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/node/actions.rb:117:in `choose'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/session.rb:808:in `block (2 levels) in <class:Session>'
     # /Users/joshua/.rvm/gems/ruby-2.4.1/gems/capybara-2.17.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/controllers/pets_controller_spec.rb:94:in `block (3 levels) in <top (required)>'

Finished in 0.89332 seconds (files took 1.56 seconds to load)
24 examples, 4 failures

Failed examples:

rspec ./spec/controllers/pets_controller_spec.rb:16 # Pets Controller new action has a form with a checkbox for existing owners
rspec ./spec/controllers/pets_controller_spec.rb:31 # Pets Controller new action creates a new pet and associates an existing owner
rspec ./spec/controllers/pets_controller_spec.rb:54 # Pets Controller new action redirects to '/pets/:id' after form submissions
rspec ./spec/controllers/pets_controller_spec.rb:91 # Pets Controller edit action edit's the pet's owner with an existing owner
```

**Comment by bbhoss** [comment]
Looking at your code, you're setting the checkbox ids to the owner's name, where the test is looking for the id. The `check` method looks for fields by name, id, or label text: http://www.rubydoc.info/github/jnicklas/capybara/Capybara/Node/Actions#check-instance_method

The tests happen to be looking for the owner id, so you could quickly fix this by switching owner name for owner id. Personally I think giving it an id of only an integer is bad. I would recommend changing the test to check `"owner_#{@owner1.id}"`
